on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
    secrets:
      personal_access_token:
        required: true
jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ inputs.config-path }}